config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'common_pages#homepage'
  get '/dashboard', to: 'common_pages#dashboard'

  scope :admin do
    get '/users', to: 'admin_users#index'
    resources :pages, except: :show
  end

  get "*url", to: 'pages#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord

  def self.homepage
    page = Page.find_by(is_homepage: true)
    unless page
      page = Page.generate_homepage 
      Page.generate_about
      Page.generate_pricing
    end
    page
  end

  def self.dashboard
    page = Page.find_by(is_dashboard: true)
    page = Page.generate_dashboard unless page
    page
  end

  def self.generate_homepage
    contents = File.read(File.join(Rails.root, "/html_pages/homepage.html"))
    create!(
      title: "Homepage",
      description: 'This is the Homepage of your application - what your users see when they first visit your App.',
      is_homepage: true,
      is_dashboard: false,
      requires_authentication: false,
      is_in_nav: false,
      body_html: contents,
      url: '/'
    )
  end

  def self.generate_dashboard
    contents = File.read(File.join(Rails.root, "/html_pages/dashboard.html"))
    create!(
      title: "Dashboard",
      description: 'This is the Dashboard of your application - what your users first see when they log in.',
      is_homepage: false,
      is_dashboard: true,
      requires_authentication: true,
      is_in_nav: false,
      body_html: contents,
      url: 'dashboard'
    )
  end

  def self.generate_about
    contents = File.read(File.join(Rails.root, "/html_pages/about.html"))
    create!(
      title: "About",
      description: 'This is an example page for you App - a common About page.',
      is_homepage: false,
      is_dashboard: false,
      requires_authentication: false,
      is_in_nav: true,
      body_html: contents,
      url: 'about'
    )
  end

  def self.generate_pricing
    contents = File.read(File.join(Rails.root, "/html_pages/pricing.html"))
    create!(
      title: "Pricing",
      description: 'This is an example page for you App - a common Pricing page.',
      is_homepage: false,
      is_dashboard: false,
      requires_authentication: false,
      is_in_nav: true,
      body_html: contents,
      url: 'pricing'
    )
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_nav_pages

  def set_nav_pages
    @nav_pages = Page.where(is_in_nav: true)
  end

  def after_sign_in_path_for(_resource_or_scope)
    dashboard_path
  end

  def after_sign_out_path_for(_resource_or_scope)
    root_path
  end

  def not_found
    fail ActionController::RoutingError, 'Not Found'
  end

  def authenticate_admin!
    authenticate_user!
    unless current_user.admin?
      redirect_to root_path, notice: "You can't go there without being an Admin."
    end
  end
end

app/controllers/common_pages_controller.rb
class CommonPagesController < ApplicationController

  def homepage
    @page = Page.homepage
  end

  def dashboard
    @page = Page.dashboard
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: %i[edit update destroy]
  before_action :authenticate_admin!, except: %i[show]

  # GET /pages or /pages.json
  def index
    @homepage = Page.homepage
    @dashboard = Page.dashboard
    pages = Page.all.where(is_dashboard: false, is_homepage: false)
    @public_pages = pages.where(requires_authentication: false)
    @private_pages = pages.where(requires_authentication: true)
  end

  # GET /pages/1 or /pages/1.json
  def show
    @page = Page.find_by(url: params[:url])
    not_found unless @page
    authenticate_user! if @page.requires_authentication?
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages or /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: "Page was successfully created." }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1 or /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to edit_page_path(@page), notice: "Page was successfully updated." }
        format.json { render :edit, status: :ok, location: @page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1 or /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: "Page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def page_params
      params.require(:page).permit(:title, :description, :is_homepage, :is_dashboard, :requires_authentication, :header_html, :is_in_nav, :body_html, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/common_pages_helper.rb
module CommonPagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin_users/index.html.erb
<%= stylesheet_link_tag '//cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.16/b-1.5.1/b-flash-1.5.1/b-html5-1.5.1/datatables.min.css' %>
<%= javascript_include_tag '//cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.16/b-1.5.1/b-flash-1.5.1/b-html5-1.5.1/datatables.min.js' %>

<div class="px-4 py-5 my-5 text-center">
  <h1 class="display-5 fw-bold">Your App Users</h1>
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4">Here you can see and search through every user that has authenticated with your app.</p>
  </div>
</div>

<div class="container px-4 pb-5">
  <div class="row g-4 pb-5 row-cols-1 row-cols-lg-3">
    <div class="col-12">
      <div class="pb-5">
        <table class="table table-hover" id="users-table">
          <thead>
            <tr>
              <td>
                Email
              </td>
              <td>
                Admin?
              </td>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <p class="mb-0">
                    <%= user.email %>
                  </p>
                </td>
                <td>
                  <% if user.admin %>
                    <span class='badge bg-primary'>YES</span>
                  <% else %>
                    <span class='badge bg-danger'>NO</span>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<script>
  
  document.addEventListener("turbolinks:load", function() {
    if ( !document.querySelector( '#users-table_wrapper' ) ) {
      var usersTable = $('#users-table').DataTable({ 
        pageLength: 25,
        dom: 'Bfrtip',
        buttons: [
          'copy', 'csv', 'excel', 'pdf'
        ]
      });
    }
  })

</script>

app/views/common_pages/_admin_panel.html.erb
<div class="row">
  <div class="col-sm-6 py-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Pages</h5>
        <p class="card-text">Manage the Pages of this Application:</p>
        <a href="<%= pages_path %>" class="btn btn-primary">View all</a>
        <a href="<%= new_page_path %>" class="btn btn-outline-primary">Create</a>
      </div>
    </div>
  </div>
  <div class="col-sm-6 py-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Users</h5>
        <p class="card-text">Manage the Users of this Application:</p>
        <a href="<%= users_path %>" class="btn btn-primary">View all</a>
      </div>
    </div>
  </div>
</div>

app/views/common_pages/dashboard.html.erb
<div class="container px-4 pb-5">
  <div class="row g-4 pb-5 row-cols-1 row-cols-lg-3">
    <div class="col-12">
      <div class="pb-5">

        <% if current_user.admin? %>

          <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item" role="presentation">
              <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">
                Admin Panel
              </button>
            </li>
            <li class="nav-item" role="presentation">
              <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button" role="tab" aria-controls="profile" aria-selected="false">
                Regular User Dashboard
              </button>
            </li>
          </ul>
          <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
              
              <%= render 'admin_panel' %>

            </div>
            <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
              <%= raw @page.body_html %>
            </div>
          </div>

        <% else %>

          <%= raw @page.body_html %>

        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/common_pages/home.html.erb
<div class="px-4 py-5 my-5 text-center">
  <h1 class="display-5 fw-bold">Welcome to your Web App</h1>
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4">In minutes, you were able to set this whole thing up (with our help, of course) and you deserve a lot of credit! Not only is this likely to be your first foray into development, but you've already done and learned a lot. Now keep at it and continue the tutorials to see how to make this App more like what you imagine it to be.</p>
    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
      <button type="button" class="btn btn-primary btn-lg px-4 gap-3">Primary button</button>
      <button type="button" class="btn btn-outline-secondary btn-lg px-4">Secondary</button>
    </div>
  </div>
</div>

<div class="container px-4 py-5" id="featured-3">
  <h2 class="pb-2 border-bottom">Columns with icons</h2>
  <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
    <div class="feature col">
      <div class="feature-icon bg-primary bg-gradient">
        <svg class="bi" width="1em" height="1em"><use xlink:href="#collection"></use></svg>
      </div>
      <h2>Featured title</h2>
      <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and probably just keep going until we run out of words.</p>
      <a href="#" class="icon-link">
        Call to action
        <svg class="bi" width="1em" height="1em"><use xlink:href="#chevron-right"></use></svg>
      </a>
    </div>
    <div class="feature col">
      <div class="feature-icon bg-primary bg-gradient">
        <svg class="bi" width="1em" height="1em"><use xlink:href="#people-circle"></use></svg>
      </div>
      <h2>Featured title</h2>
      <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and probably just keep going until we run out of words.</p>
      <a href="#" class="icon-link">
        Call to action
        <svg class="bi" width="1em" height="1em"><use xlink:href="#chevron-right"></use></svg>
      </a>
    </div>
    <div class="feature col">
      <div class="feature-icon bg-primary bg-gradient">
        <svg class="bi" width="1em" height="1em"><use xlink:href="#toggles2"></use></svg>
      </div>
      <h2>Featured title</h2>
      <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and probably just keep going until we run out of words.</p>
      <a href="#" class="icon-link">
        Call to action
        <svg class="bi" width="1em" height="1em"><use xlink:href="#chevron-right"></use></svg>
      </a>
    </div>
  </div>
</div>


<div class="container px-4 py-5" id="custom-cards">
  <h2 class="pb-2 border-bottom">Custom cards</h2>

  <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">
    <div class="col">
      <div class="card card-cover h-100 overflow-hidden text-white bg-dark rounded-5 shadow-lg" style="background-image: url('unsplash-photo-1.jpg');">
        <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
          <h2 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">Short title, long jacket</h2>
          <ul class="d-flex list-unstyled mt-auto">
            <li class="me-auto">
              <img src="https://github.com/twbs.png" alt="Bootstrap" width="32" height="32" class="rounded-circle border border-white">
            </li>
            <li class="d-flex align-items-center me-3">
              <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"></use></svg>
              <small>Earth</small>
            </li>
            <li class="d-flex align-items-center">
              <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#calendar3"></use></svg>
              <small>3d</small>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="col">
      <div class="card card-cover h-100 overflow-hidden text-white bg-dark rounded-5 shadow-lg" style="background-image: url('unsplash-photo-2.jpg');">
        <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
          <h2 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">Much longer title that wraps to multiple lines</h2>
          <ul class="d-flex list-unstyled mt-auto">
            <li class="me-auto">
              <img src="https://github.com/twbs.png" alt="Bootstrap" width="32" height="32" class="rounded-circle border border-white">
            </li>
            <li class="d-flex align-items-center me-3">
              <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"></use></svg>
              <small>Pakistan</small>
            </li>
            <li class="d-flex align-items-center">
              <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#calendar3"></use></svg>
              <small>4d</small>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="col">
      <div class="card card-cover h-100 overflow-hidden text-white bg-dark rounded-5 shadow-lg" style="background-image: url('unsplash-photo-3.jpg');">
        <div class="d-flex flex-column h-100 p-5 pb-3 text-shadow-1">
          <h2 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">Another longer title belongs here</h2>
          <ul class="d-flex list-unstyled mt-auto">
            <li class="me-auto">
              <img src="https://github.com/twbs.png" alt="Bootstrap" width="32" height="32" class="rounded-circle border border-white">
            </li>
            <li class="d-flex align-items-center me-3">
              <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"></use></svg>
              <small>California</small>
            </li>
            <li class="d-flex align-items-center">
              <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#calendar3"></use></svg>
              <small>5d</small>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/common_pages/homepage.html.erb
<%= raw @page.body_html %>

app/views/common_pages/pricing.html.erb
<div class="container py-3">
  <header>
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
      <h1 class="display-4 fw-normal">Pricing</h1>
      <p class="fs-5 text-muted">Quickly build an effective pricing table for your potential customers with this Bootstrap example. It’s built with default Bootstrap components and utilities with little customization.</p>
    </div>
  </header>

  <main>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
      <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
          <div class="card-header py-3">
            <h4 class="my-0 fw-normal">Free</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">$0<small class="text-muted fw-light">/mo</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>10 users included</li>
              <li>2 GB of storage</li>
              <li>Email support</li>
              <li>Help center access</li>
            </ul>
            <button type="button" class="w-100 btn btn-lg btn-outline-primary">Sign up for free</button>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
          <div class="card-header py-3">
            <h4 class="my-0 fw-normal">Pro</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">$15<small class="text-muted fw-light">/mo</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>20 users included</li>
              <li>10 GB of storage</li>
              <li>Priority email support</li>
              <li>Help center access</li>
            </ul>
            <button type="button" class="w-100 btn btn-lg btn-primary">Get started</button>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm border-primary">
          <div class="card-header py-3 text-white bg-primary border-primary">
            <h4 class="my-0 fw-normal">Enterprise</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">$29<small class="text-muted fw-light">/mo</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>30 users included</li>
              <li>15 GB of storage</li>
              <li>Phone and email support</li>
              <li>Help center access</li>
            </ul>
            <button type="button" class="w-100 btn btn-lg btn-primary">Contact us</button>
          </div>
        </div>
      </div>
    </div>

    <h2 class="display-6 text-center mb-4">Compare plans</h2>

    <div class="table-responsive">
      <table class="table text-center">
        <thead>
          <tr>
            <th style="width: 34%;"></th>
            <th style="width: 22%;">Free</th>
            <th style="width: 22%;">Pro</th>
            <th style="width: 22%;">Enterprise</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row" class="text-start">Public</th>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"></use></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"></use></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"></use></svg></td>
          </tr>
          <tr>
            <th scope="row" class="text-start">Private</th>
            <td></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"></use></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"></use></svg></td>
          </tr>
        </tbody>

        <tbody>
          <tr>
            <th scope="row" class="text-start">Permissions</th>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"></use></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"></use></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"></use></svg></td>
          </tr>
          <tr>
            <th scope="row" class="text-start">Sharing</th>
            <td></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"></use></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"></use></svg></td>
          </tr>
          <tr>
            <th scope="row" class="text-start">Unlimited members</th>
            <td></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"></use></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"></use></svg></td>
          </tr>
          <tr>
            <th scope="row" class="text-start">Extra security</th>
            <td></td>
            <td></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"></use></svg></td>
          </tr>
        </tbody>
      </table>
    </div>
  </main>

  <footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <small class="d-block mb-3 text-muted">© 2017–2021</small>
      </div>
      <div class="col-6 col-md">
        <h5>Features</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Cool stuff</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Random feature</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Team feature</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Stuff for developers</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Another one</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Last time</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Resource</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Resource name</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Another resource</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Final resource</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Team</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Locations</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Privacy</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Terms</a></li>
        </ul>
      </div>
    </div>
  </footer>
</div>

app/views/layouts/_flash_messages.html.erb
<div class="text-center" role="alert">
  <% if flash[ :success ] %>
    <div class="alert alert-success fade show mb-0" role="alert">
      <%= flash[ :success ] %>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-danger fade show mb-0" role="alert">
      <%= alert %>
    </div>
  <% end %>
  <% if notice %>
    <div class="alert alert-success fade show mb-0" role="alert">
      <%= notice %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rapid App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
      <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
          <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
          <span class="fs-4">Rapid App</span>
        </a>

        <ul class="nav nav-pills">
          <% @nav_pages.each do |nav_page| %>
            <li class="nav-item"><a href="<%= nav_page.url %>" class="nav-link"><%= nav_page.title %></a></li>
          <% end %>
          <% if current_user %>
            <li class="border-start nav-item"><a href="/dashboard" class="nav-link">Dashboard</a></li>
            <li class="nav-item"><a href=<%= destroy_user_session_path %> data-method="delete" class="nav-link">Sign Out</a></li>
          <% else %>
            <li class="border-start nav-item"><a href="/users/sign_in" class="nav-link">Log in</a></li>
            <li class="nav-item"><a href="/users/sign_up" class="nav-link">Sign Up</a></li>
          <% end %>
        </ul>
      </header>

      <%= render 'layouts/flash_messages' %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/pages/edit.html.erb
<div class="px-4 pt-5 mt-5 text-center">
  <h1 class="display-5 fw-bold">Editing Page</h1>
</div>

<div class="container px-4 py-5" id="featured-3">
  <div class="row pb-4">
    <div class="col-12">
      <%= render 'form', page: @page %>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<div class="px-4 pt-5 mt-5 text-center">
  <h1 class="display-5 fw-bold">Your App Pages</h1>
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4">This is a list of all of the pages your App has. Manage them below.</p>
    <%= link_to 'New Page', new_page_path, class: 'btn btn-outline-primary btn-lg' %>
  </div>
</div>

<div class="container px-4 py-5" id="featured-3">
  <div class="row pb-4">
    <div class="col-12">
      <h4 class='border-bottom mb-2'>Public Pages:</h4>
    </div>
    <div class="col-12 py-3">
      <%= link_to edit_page_path(@homepage) do %>
        <div class="card rounded p-3 bg-primary bg-gradient">
          <h2 class='text-white'><%= @homepage.title %></h2>
          <p class='text-white'><%= @homepage.description %></p>
        </div>
      <% end %>
    </div>
    <% @public_pages.each do |page| %>
      <div class="col-12 py-3">
        <%= link_to edit_page_path(page) do %>
          <div class="card rounded p-3 bg-primary bg-gradient" style="opacity: .8;">
            <h2 class='text-white'><%= page.title %></h2>
            <p class='text-white'><%= page.description %></p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="row pb-4">
    <div class="col-12">
      <h4 class='border-bottom mb-2'>Pages that require Authentication:</h4>
    </div>
    <div class="col-12 py-3">
      <%= link_to edit_page_path(@dashboard) do %>
        <div class="card rounded p-3 bg-success bg-gradient">
          <h2 class='text-white'><%= @dashboard.title %></h2>
          <p class='text-white'><%= @dashboard.description %></p>
        </div>
      <% end %>
    </div>
    <% @private_pages.each do |page| %>
      <div class="col-12 py-3">
        <%= link_to edit_page_path(page) do %>
          <div class="card rounded p-3 bg-success bg-gradient" style="opacity: .8;">
            <h2 class='text-white'><%= page.title %></h2>
            <p class='text-white'><%= page.description %></p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/new.html.erb
<div class="px-4 pt-5 mt-5 text-center">
  <h1 class="display-5 fw-bold">Create a New Page</h1>
</div>

<div class="container px-4 py-5" id="featured-3">
  <div class="row pb-4">
    <div class="col-12">
      <%= render 'form', page: @page %>
    </div>
  </div>
</div>

app/views/pages/show.html.erb
<%= raw @page.body_html %>